from django.urls import path
from serviceapp.views import ActivateUserView, AmoCRMContactUpdateView, AmoCRMWebhookView, BalanceDepositConfirmView, BalanceDepositView, ClientCityUpdateView, ClientPhoneUpdateView, ClientRequestInfoView, ClientRequestsView, ClientReviewUpdateView, DeactivateUserView, MasterBalanceView, MasterCityUpdateView, MasterEquipmentUpdateView, MasterFreeRequestsView, MasterGroupCheckCallbackView, MasterNameUpdateView, MasterPhoneUpdateView, MasterProfileView, MasterServiceUpdateView, MasterStatisticsView, MasterStatsView, ServiceEquipmentTypesView, UpdateServiceRequestRatingView, UserRegistrationView, ServiceRequestCreateView, ServiceRequestHistoryView, MasterActiveRequestsView, AssignRequestView, CloseRequestView, UserProfileView, FinishRequestView

urlpatterns = [
    path('register/', UserRegistrationView.as_view(), name='user_registration'),
    path('create_request/', ServiceRequestCreateView.as_view(), name='create_request'),
    path('requests_history/', ServiceRequestHistoryView.as_view(), name='requests_history'),
    path('master_active_requests/', MasterActiveRequestsView.as_view(), name='master_active_requests'),
    path('master_free_requests/', MasterFreeRequestsView.as_view(), name='master_free_requests'),
    path('assign_request/', AssignRequestView.as_view(), name='assign_request'),
    path('close_request/', CloseRequestView.as_view(), name='close_request'),
    path('finish_request/', FinishRequestView.as_view(), name='finish_request'),
    path('profile/', UserProfileView.as_view(), name='user_profile'),
    path('types/', ServiceEquipmentTypesView.as_view(), name='service_equipment_types'),
    path('amocrm-webhook/', AmoCRMWebhookView.as_view(), name='amocrm_webhook'),
    path('master_statistics/', MasterStatisticsView.as_view(), name='master_statistics'),
    path('client_requests/', ClientRequestsView.as_view(), name='client_requests'),
    path('client_request_info/', ClientRequestInfoView.as_view(), name = 'client_request_info'),
    path('master_stats/', MasterStatsView.as_view(), name='master_stats'),
    path('balance_deposit/', BalanceDepositView.as_view(), name='balance_deposit'),
    path('balance_deposit_confirm/', BalanceDepositConfirmView.as_view(), name='balance_deposit_confirm'),
    path('users/deactivate/', DeactivateUserView.as_view(), name='deactivate-user'),
    path('users/activate/', ActivateUserView.as_view(), name='activate-user'),
    path('master_profile/', MasterProfileView.as_view(), name='master-profile'),
    path('master_update_city/', MasterCityUpdateView.as_view(), name='master-update-city'),
    path('master_update_equipment/', MasterEquipmentUpdateView.as_view(), name='master-update-equipment'),
    path('master_update_phone/', MasterPhoneUpdateView.as_view(), name='master-update-phone'),
    path('master_update_name/', MasterNameUpdateView.as_view(), name='master-update-name'),
    path('client_update_phone/', ClientPhoneUpdateView.as_view(), name='client-update-phone'),
    path('client_update_city/', ClientCityUpdateView.as_view(), name='client-update-city'),
    path('master_update_service/', MasterServiceUpdateView.as_view(), name='master-update-service'),
    path('amocrm_update_contact/', AmoCRMContactUpdateView.as_view(), name='amocrm-update-contact'),
    path('update_request_rating/', UpdateServiceRequestRatingView.as_view(), name='update-request-rating'),
    path('master_balance/', MasterBalanceView.as_view(), name='master-balance'),
    path('client_review_update/', ClientReviewUpdateView.as_view(), name='client-review-update'),
    path('master_group_check_callback/', MasterGroupCheckCallbackView.as_view(), name='master-group-check-callback')
]
