"""
Django settings for myproject project.

Generated by 'django-admin startproject' using Django 5.1.2.

For more information on this file, see
https://docs.djangoproject.com/en/5.1/topics/settings/

For the full list of settings and their values, see
https://docs.djangoproject.com/en/5.1/ref/settings/
"""

from pathlib import Path

# Build paths inside the project like this: BASE_DIR / 'subdir'.
BASE_DIR = Path(__file__).resolve().parent.parent


# Quick-start development settings - unsuitable for production
# See https://docs.djangoproject.com/en/5.1/howto/deployment/checklist/

# SECURITY WARNING: keep the secret key used in production secret!
SECRET_KEY = 'django-insecure-xp8lc#&_5+x-$tq0iyzmi5azb82)c&arrrx_2yx0q7cspz&8+7'

# SECURITY WARNING: don't run with debug turned on in production!
DEBUG = True

ALLOWED_HOSTS = ['servicehome.onrender.com', '127.0.0.1']


# Application definition

INSTALLED_APPS = [
    'django.contrib.admin',
    'django.contrib.auth',
    'django.contrib.contenttypes',
    'django.contrib.sessions',
    'django.contrib.messages',
    'django.contrib.staticfiles',
    'serviceapp',
    'drf_yasg',
]

MIDDLEWARE = [
    'django.middleware.security.SecurityMiddleware',
    'whitenoise.middleware.WhiteNoiseMiddleware',
    'django.contrib.sessions.middleware.SessionMiddleware',
    'django.middleware.common.CommonMiddleware',
    'django.middleware.csrf.CsrfViewMiddleware',
    'django.contrib.auth.middleware.AuthenticationMiddleware',
    'django.contrib.messages.middleware.MessageMiddleware',
    'django.middleware.clickjacking.XFrameOptionsMiddleware',
]

ROOT_URLCONF = 'myproject.urls'

REST_FRAMEWORK = {
    'DEFAULT_PERMISSION_CLASSES': [
        'rest_framework.permissions.AllowAny',  # Разрешить доступ всем по умолчанию
    ],
    'DEFAULT_AUTHENTICATION_CLASSES': [
        # Уберите или оставьте ваши текущие методы аутентификации
        # 'rest_framework.authentication.TokenAuthentication',
    ],
}

TEMPLATES = [
    {
        'BACKEND': 'django.template.backends.django.DjangoTemplates',
        'DIRS': [],
        'APP_DIRS': True,
        'OPTIONS': {
            'context_processors': [
                'django.template.context_processors.debug',
                'django.template.context_processors.request',
                'django.contrib.auth.context_processors.auth',
                'django.contrib.messages.context_processors.messages',
            ],
        },
    },
]

WSGI_APPLICATION = 'myproject.wsgi.application'


# Database
# https://docs.djangoproject.com/en/5.1/ref/settings/#databases

import dj_database_url

DATABASES = {
    'default': dj_database_url.parse('postgresql://servicehome_user:eBEg9eZih642h8tRJwusOy8fH47O0yEr@dpg-cttdq3popnds73cc0l5g-a.oregon-postgres.render.com/servicehome')
}


# Password validation
# https://docs.djangoproject.com/en/5.1/ref/settings/#auth-password-validators

AUTH_PASSWORD_VALIDATORS = [
    {
        'NAME': 'django.contrib.auth.password_validation.UserAttributeSimilarityValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.MinimumLengthValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.CommonPasswordValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.NumericPasswordValidator',
    },
]


# Internationalization
# https://docs.djangoproject.com/en/5.1/topics/i18n/

LANGUAGE_CODE = 'en-us'

TIME_ZONE = 'UTC'

USE_I18N = True

USE_TZ = True



# Default primary key field type
# https://docs.djangoproject.com/en/5.1/ref/settings/#default-auto-field

DEFAULT_AUTO_FIELD = 'django.db.models.BigAutoField'
import os
# URL для статических файлов
STATIC_URL = '/static/'

# Путь к директории, куда будут собраны статические файлы
STATIC_ROOT = os.path.join(BASE_DIR, 'staticfiles')

# Дополнительные директории с статическими файлами (если есть)
STATICFILES_DIRS = [
    os.path.join(BASE_DIR, 'static'),
]

# Использование WhiteNoise для сжатия и оптимизации статических файлов
STATICFILES_STORAGE = 'whitenoise.storage.CompressedManifestStaticFilesStorage'


AMOCRM_BEARER_TOKEN = os.getenv('AMOCRM_BEARER_TOKEN', 'eyJ0eXAiOiJKV1QiLCJhbGciOiJSUzI1NiIsImp0aSI6Ijc2OGRmOTA0ZjQ4MWEzOTY2Y2I3MjdjM2U4ZmUwZmFlYTRiN2VkNzhjMTMwZjE0YjFlOTc2MjBlNzU3MzFhYmExMmJhNjBkMjQwMGEzMzM4In0.eyJhdWQiOiI2MDE3NjYwYS1hOTBjLTRmODItYTg2ZS1kNGI5MGEwNDNjNDciLCJqdGkiOiI3NjhkZjkwNGY0ODFhMzk2NmNiNzI3YzNlOGZlMGZhZWE0YjdlZDc4YzEzMGYxNGIxZTk3NjIwZTc1NzMxYWJhMTJiYTYwZDI0MDBhMzMzOCIsImlhdCI6MTczODUzMzE4MiwibmJmIjoxNzM4NTMzMTgyLCJleHAiOjE3Mzg2MTk1ODIsInN1YiI6IjU3MjAwNzQiLCJncmFudF90eXBlIjoiIiwiYWNjb3VudF9pZCI6Mjg3MzM2ODMsImJhc2VfZG9tYWluIjoiYW1vY3JtLnJ1IiwidmVyc2lvbiI6Miwic2NvcGVzIjpbInB1c2hfbm90aWZpY2F0aW9ucyIsImZpbGVzIiwiY3JtIiwiZmlsZXNfZGVsZXRlIiwibm90aWZpY2F0aW9ucyJdLCJoYXNoX3V1aWQiOiIxODI2ODNiMC02YTBjLTQ3NTEtOWYwNi03MjU4NDcxNzA2MzAiLCJhcGlfZG9tYWluIjoiYXBpLWIuYW1vY3JtLnJ1In0.B11IxwQp69WLhL4bEIJz4CCcwn4oxDDzgdiUlIBtStmqMYgPzXLtyyFeUYWIJp5wwbKR_BTD3JMjuaavUe6BmmS5z7DF_KaEAkQa6zAqkKdLOcHsWh5Lu3W9ZSt61AEaAeNXC52iFw0UTgZGY-nRwik4DbQy-6VeqQJeMXOpjM3uHbEICEnlxPbdrKzHqfT1pT4iwi2nx5dQPnRqQBoJvZ00lGylgkPBXAyXCrq2fB5l5Bs5AfRYn2xVcPrqDinxMdBCkLfVhW5n5RjSl48HmJrNJSHqLHRGwTvgffSf1SeBSQGjmK5N7P6eKqAsKU0ohLm-2kUlle7h2Ej1xUyivw')  
AMOCRM_SUBDOMAIN = os.getenv('AMOCRM_SUBDOMAIN', 'servicecentru') 

AMOCRM_CUSTOM_FIELD_TELEGRAM_ID = 744499

API_ACCESS_TOKEN = ''


# settings.py

LOGGING = {
    'version': 1,
    'disable_existing_loggers': False,
    'formatters': {
        'verbose': {
            'format': '[{asctime}] {levelname} {name} {message}',
            'style': '{',
        },
        'simple': {
            'format': '{levelname} {message}',
            'style': '{',
        },
    },
    'handlers': {
        'console': {
            'class': 'logging.StreamHandler',
            'formatter': 'verbose',
        },
        'file': {
            'level': 'DEBUG',
            'class': 'logging.FileHandler',
            'filename': 'amocrm_webhook.log',
            'formatter': 'verbose',
        },
    },
    'loggers': {
        'serviceapp': {  # Замените 'serviceapp' на имя вашего приложения, если отличается
            'handlers': ['console', 'file'],
            'level': 'DEBUG',  # Устанавливаем уровень на DEBUG для захвата всех сообщений
            'propagate': True,
        },
    },
}
