# Generated by Django 5.1.4 on 2024-12-18 17:50

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('serviceapp', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='user',
            old_name='email',
            new_name='telegram_login',
        ),
    ]
