# Generated by Django 5.1.2 on 2024-12-22 21:52

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('serviceapp', '0002_rename_email_user_telegram_login'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='servicerequest',
            name='city',
        ),
        migrations.RemoveField(
            model_name='master',
            name='city',
        ),
        migrations.RemoveField(
            model_name='masterservice',
            name='master',
        ),
        migrations.RemoveField(
            model_name='masterservice',
            name='service',
        ),
        migrations.RemoveField(
            model_name='servicerequest',
            name='service',
        ),
        migrations.AddField(
            model_name='master',
            name='city_name',
            field=models.CharField(blank=True, help_text='Название города', max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='servicerequest',
            name='city_name',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='servicerequest',
            name='service_name',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='user',
            name='city_name',
            field=models.CharField(blank=True, help_text='Название города', max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='master',
            name='user',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='master_profile', to='serviceapp.user'),
        ),
        migrations.AlterField(
            model_name='user',
            name='telegram_id',
            field=models.CharField(blank=True, max_length=255, null=True, unique=True),
        ),
        migrations.AlterField(
            model_name='user',
            name='telegram_login',
            field=models.CharField(blank=True, max_length=255, null=True, unique=True),
        ),
        migrations.DeleteModel(
            name='City',
        ),
        migrations.DeleteModel(
            name='MasterService',
        ),
        migrations.DeleteModel(
            name='Service',
        ),
    ]
