# Generated by Django 5.1.2 on 2024-12-25 17:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('serviceapp', '0003_remove_servicerequest_city_remove_master_city_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='master',
            name='service_name',
            field=models.CharField(blank=True, help_text='Название услуги', max_length=255, null=True),
        ),
    ]
