# Generated by Django 5.1.2 on 2024-12-25 17:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('serviceapp', '0004_master_service_name'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='amo_crm_contact_id',
            field=models.IntegerField(blank=True, help_text='ID контакта в AmoCRM', null=True, unique=True),
        ),
        migrations.AlterField(
            model_name='user',
            name='city_name',
            field=models.CharField(blank=True, help_text='Название города пользователя', max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='user',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, help_text='Дата и время создания записи'),
        ),
        migrations.AlterField(
            model_name='user',
            name='name',
            field=models.CharField(help_text='Имя пользователя', max_length=255),
        ),
        migrations.AlterField(
            model_name='user',
            name='phone',
            field=models.CharField(blank=True, help_text='Телефон', max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='user',
            name='role',
            field=models.CharField(choices=[('Client', 'Client'), ('Master', 'Master'), ('Admin', 'Admin')], default='Client', help_text='Роль пользователя в системе', max_length=20),
        ),
        migrations.AlterField(
            model_name='user',
            name='telegram_id',
            field=models.CharField(blank=True, help_text='Telegram ID пользователя', max_length=255, null=True, unique=True),
        ),
        migrations.AlterField(
            model_name='user',
            name='telegram_login',
            field=models.CharField(blank=True, help_text='Telegram логин пользователя', max_length=255, null=True, unique=True),
        ),
    ]
