# Generated by Django 5.1.2 on 2024-12-25 20:34

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('serviceapp', '0005_user_amo_crm_contact_id_alter_user_city_name_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='servicerequest',
            name='amo_crm_lead_id',
            field=models.IntegerField(blank=True, help_text='ID лида в AmoCRM', null=True, unique=True),
        ),
        migrations.AddField(
            model_name='servicerequest',
            name='equipment_brand',
            field=models.CharField(blank=True, help_text='Марка оборудования (например, LG, Samsung)', max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='servicerequest',
            name='equipment_model',
            field=models.CharField(blank=True, help_text='Модель оборудования', max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='servicerequest',
            name='equipment_type',
            field=models.CharField(blank=True, help_text='Тип оборудования (например, стиральная машина)', max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='user',
            name='referral_link',
            field=models.CharField(blank=True, help_text='Содержимое команды /start (реф. строка)', max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='user',
            name='referrer',
            field=models.ForeignKey(blank=True, help_text='Кто пригласил пользователя', null=True, on_delete=django.db.models.deletion.SET_NULL, to='serviceapp.user'),
        ),
        migrations.AlterField(
            model_name='user',
            name='city_name',
            field=models.CharField(blank=True, help_text='Город пользователя', max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='user',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True),
        ),
        migrations.AlterField(
            model_name='user',
            name='role',
            field=models.CharField(choices=[('Client', 'Client'), ('Master', 'Master'), ('Admin', 'Admin')], default='Client', help_text='Роль пользователя (Client/Master/Admin)', max_length=20),
        ),
    ]
