# Generated by Django 5.1.2 on 2024-12-27 16:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('serviceapp', '0006_servicerequest_amo_crm_lead_id_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='EquipmentType',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(help_text='Название типа оборудования', max_length=255, unique=True)),
                ('fields', models.JSONField(help_text='Поля типа оборудования (можно хранить как JSON)')),
            ],
        ),
        migrations.CreateModel(
            name='ServiceType',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(help_text='Название типа сервиса', max_length=255, unique=True)),
            ],
        ),
    ]
