# Generated by Django 5.1.2 on 2024-12-27 16:28

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('serviceapp', '0007_equipmenttype_servicetype'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='equipmenttype',
            name='fields',
        ),
    ]
