# Generated by Django 5.1.2 on 2024-12-27 17:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('serviceapp', '0008_remove_equipmenttype_fields'),
    ]

    operations = [
        migrations.AddField(
            model_name='master',
            name='equipment_type_name',
            field=models.CharField(blank=True, help_text='Тип оборудования мастера', max_length=255, null=True),
        ),
    ]
