# Generated by Django 5.1.2 on 2024-12-27 19:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('serviceapp', '0009_master_equipment_type_name'),
    ]

    operations = [
        migrations.AddField(
            model_name='servicerequest',
            name='amo_status_code',
            field=models.IntegerField(blank=True, help_text='Внешний статус заявки (например, из AmoCRM)', null=True),
        ),
        migrations.AlterField(
            model_name='servicerequest',
            name='status',
            field=models.CharField(choices=[('Open', 'Новая заявка'), ('In Progress', 'Взяли в работу'), ('Completed', 'Успешно реализовано'), ('Cancelled', 'Отказ от ремонта'), ('Free', 'Свободная заявка')], default='Open', max_length=20),
        ),
    ]
