# Generated by Django 5.1.2 on 2025-01-05 18:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('serviceapp', '0010_servicerequest_amo_status_code_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='master',
            name='balance',
            field=models.DecimalField(decimal_places=2, default=0.0, help_text='Баланс мастера', max_digits=10),
        ),
    ]
