# Generated by Django 5.1.2 on 2025-01-10 18:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('serviceapp', '0011_alter_master_balance'),
    ]

    operations = [
        migrations.AlterField(
            model_name='servicerequest',
            name='status',
            field=models.CharField(choices=[('Open', 'Новая заявка'), ('In Progress', 'Взяли в работу'), ('Completed', 'Успешно реализовано'), ('Cancelled', 'Отказ от ремонта'), ('Free', 'Свободная заявка'), ('AwaitingClosure', 'Ожидает закрытия'), ('Closed', 'Закрыто')], default='Open', max_length=20),
        ),
    ]
