# Generated by Django 5.1.2 on 2025-01-11 13:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('serviceapp', '0012_alter_servicerequest_status'),
    ]

    operations = [
        migrations.AddField(
            model_name='servicerequest',
            name='comment_after_finish',
            field=models.TextField(blank=True, help_text='Комментарий мастера после завершения работ', null=True),
        ),
        migrations.AddField(
            model_name='servicerequest',
            name='spare_parts_spent',
            field=models.DecimalField(blank=True, decimal_places=2, help_text='Сумма, потраченная на запчасти', max_digits=10, null=True),
        ),
        migrations.AddField(
            model_name='servicerequest',
            name='warranty',
            field=models.CharField(blank=True, help_text='Гарантия (например, 6 месяцев)', max_length=255, null=True),
        ),
    ]
