# Generated by Django 5.1.2 on 2025-01-11 14:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('serviceapp', '0013_servicerequest_comment_after_finish_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='servicerequest',
            name='status',
            field=models.CharField(choices=[('Open', 'Новая заявка'), ('In Progress', 'Взяли в работу'), ('Completed', 'Успешно реализовано'), ('Cancelled', 'Отказ от ремонта'), ('Free', 'Свободная заявка'), ('AwaitingClosure', 'Ожидает закрытия'), ('Closed', 'Закрыто'), ('QualityControl', 'Контроль качества')], default='Open', max_length=20),
        ),
    ]
