# Generated by Django 5.1.2 on 2025-02-03 15:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('serviceapp', '0016_transaction_status'),
    ]

    operations = [
        migrations.CreateModel(
            name='Settings',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('comission', models.DecimalField(decimal_places=2, default=0.0, help_text='Процент комиссии, который будет списываться с суммы сделки.', max_digits=5)),
            ],
        ),
        migrations.RemoveField(
            model_name='referrallink',
            name='bonus_amount',
        ),
        migrations.AddField(
            model_name='servicerequest',
            name='crm_operator_comment',
            field=models.TextField(blank=True, help_text='Комментарий оператора из AmoCRM', null=True),
        ),
        migrations.AddField(
            model_name='user',
            name='balance',
            field=models.DecimalField(decimal_places=2, default=0.0, help_text='Баланс клиента', max_digits=10),
        ),
    ]
