# Generated by Django 5.1.2 on 2025-02-03 15:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('serviceapp', '0017_settings_remove_referrallink_bonus_amount_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='settings',
            name='amocrm_bearer_token',
            field=models.TextField(default='', help_text='Токен для аутентификации в AmoCRM'),
        ),
    ]
