# Generated by Django 5.1.2 on 2025-02-08 13:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('serviceapp', '0018_settings_amocrm_bearer_token'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='settings',
            name='comission',
        ),
        migrations.AddField(
            model_name='master',
            name='level',
            field=models.IntegerField(default=1, help_text='Уровень мастера'),
        ),
        migrations.AddField(
            model_name='settings',
            name='commission_level1',
            field=models.DecimalField(decimal_places=2, default=0.0, help_text='Процент комиссии для уровня 1', max_digits=5),
        ),
        migrations.AddField(
            model_name='settings',
            name='commission_level2',
            field=models.DecimalField(decimal_places=2, default=0.0, help_text='Процент комиссии для уровня 2', max_digits=5),
        ),
        migrations.AddField(
            model_name='settings',
            name='commission_level3',
            field=models.DecimalField(decimal_places=2, default=0.0, help_text='Процент комиссии для уровня 3', max_digits=5),
        ),
        migrations.AddField(
            model_name='settings',
            name='max_requests_level1',
            field=models.PositiveIntegerField(default=1, help_text='Максимальное число заявок в работе для уровня 1'),
        ),
        migrations.AddField(
            model_name='settings',
            name='max_requests_level2',
            field=models.PositiveIntegerField(default=3, help_text='Максимальное число заявок в работе для уровня 2'),
        ),
        migrations.AddField(
            model_name='settings',
            name='max_requests_level3',
            field=models.PositiveIntegerField(default=5, help_text='Максимальное число заявок в работе для уровня 3'),
        ),
    ]
