# Generated by Django 5.1.2 on 2025-02-12 12:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('serviceapp', '0019_remove_settings_comission_master_level_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='servicerequest',
            name='deal_success',
            field=models.CharField(blank=True, help_text='Успех сделки', max_length=255, null=True),
        ),
    ]
