# Generated by Django 5.1.2 on 2025-02-19 17:49

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('serviceapp', '0020_servicerequest_deal_success'),
    ]

    operations = [
        migrations.AddField(
            model_name='equipmenttype',
            name='service_type',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='equipment_types', to='serviceapp.servicetype'),
        ),
    ]
