# Generated by Django 5.1.2 on 2025-02-19 18:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('serviceapp', '0021_equipmenttype_service_type'),
    ]

    operations = [
        migrations.AddField(
            model_name='servicetype',
            name='commission_level_1',
            field=models.DecimalField(blank=True, decimal_places=2, help_text='Комиссия 1-го уровня (в условных единицах, например, в рублях или процентах)', max_digits=7, null=True, verbose_name='Комиссия 1-го уровня'),
        ),
        migrations.AddField(
            model_name='servicetype',
            name='commission_level_2',
            field=models.DecimalField(blank=True, decimal_places=2, help_text='Комиссия 2-го уровня (в условных единицах, например, в рублях или процентах)', max_digits=7, null=True, verbose_name='Комиссия 2-го уровня'),
        ),
        migrations.AddField(
            model_name='servicetype',
            name='commission_level_3',
            field=models.DecimalField(blank=True, decimal_places=2, help_text='Комиссия 3-го уровня (в условных единицах, например, в рублях или процентах)', max_digits=7, null=True, verbose_name='Комиссия 3-го уровня'),
        ),
    ]
