# Generated by Django 5.1.2 on 2025-02-22 17:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('serviceapp', '0022_servicetype_commission_level_1_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='is_active',
            field=models.BooleanField(default=True, help_text='Активен ли пользователь'),
        ),
    ]
