# Generated by Django 5.1.2 on 2025-02-22 18:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('serviceapp', '0023_user_is_active'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='telegram_id',
            field=models.CharField(blank=True, help_text='Telegram ID пользователя', max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='user',
            name='telegram_login',
            field=models.CharField(blank=True, help_text='Telegram логин пользователя', max_length=255, null=True),
        ),
    ]
