# Generated by Django 5.1.2 on 2025-02-28 17:16

import django.db.models.deletion
from decimal import Decimal
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('serviceapp', '0024_alter_user_telegram_id_alter_user_telegram_login'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='transaction',
            name='user',
        ),
        migrations.AddField(
            model_name='transaction',
            name='client',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='transactions', to='serviceapp.user'),
        ),
        migrations.AddField(
            model_name='transaction',
            name='master',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='transactions', to='serviceapp.master'),
        ),
        migrations.AlterField(
            model_name='transaction',
            name='transaction_type',
            field=models.CharField(choices=[('Deposit', 'Deposit'), ('Comission', 'Comission'), ('Penalty', 'Penalty')], max_length=20),
        ),
        migrations.CreateModel(
            name='WorkOutcome',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('is_penalty', models.BooleanField(default=False, help_text='Признак штрафа')),
                ('is_success', models.BooleanField(default=False, help_text='Признак успеха')),
                ('penalty_amount', models.DecimalField(decimal_places=2, default=Decimal('0.00'), help_text='Сумма штрафа', max_digits=10)),
                ('user_message', models.TextField(blank=True, help_text='Текст пользователю', null=True)),
                ('outcome_name', models.CharField(help_text='Название итога работы', max_length=255)),
                ('service_request', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='work_outcome_record', to='serviceapp.servicerequest')),
            ],
        ),
        migrations.AddField(
            model_name='servicerequest',
            name='work_outcome',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='service_request_outcome', to='serviceapp.workoutcome'),
        ),
    ]
