# Generated by Django 5.1.2 on 2025-03-01 17:17

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('serviceapp', '0025_remove_transaction_user_transaction_client_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='servicerequest',
            name='competence_rating',
            field=models.PositiveSmallIntegerField(blank=True, help_text='Компетентность мастера (от 1 до 5)', null=True),
        ),
        migrations.AddField(
            model_name='servicerequest',
            name='quality_rating',
            field=models.PositiveSmallIntegerField(blank=True, help_text='Качество работ (от 1 до 5)', null=True),
        ),
        migrations.AddField(
            model_name='servicerequest',
            name='recommendation_rating',
            field=models.PositiveSmallIntegerField(blank=True, help_text='Готовность рекомендовать (от 1 до 5)', null=True),
        ),
        migrations.AddField(
            model_name='transaction',
            name='service_request',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='transactions', to='serviceapp.servicerequest'),
        ),
    ]
