# Generated by Django 5.1.2 on 2025-03-02 16:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('serviceapp', '0026_servicerequest_competence_rating_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='settings',
            name='service_token',
            field=models.CharField(default='', help_text='Токен для доступа к API сервиса', max_length=255),
        ),
    ]
