# Generated by Django 5.1.2 on 2025-03-02 17:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('serviceapp', '0027_settings_service_token'),
    ]

    operations = [
        migrations.AddField(
            model_name='servicerequest',
            name='client_review',
            field=models.TextField(blank=True, help_text='Отзыв клиента', null=True),
        ),
    ]
