# Generated by Django 5.1.2 on 2025-03-03 17:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('serviceapp', '0028_servicerequest_client_review'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='settings',
            name='commission_level1',
        ),
        migrations.RemoveField(
            model_name='settings',
            name='commission_level2',
        ),
        migrations.RemoveField(
            model_name='settings',
            name='commission_level3',
        ),
        migrations.AddField(
            model_name='settings',
            name='required_invites_level2',
            field=models.IntegerField(default=1, help_text='Требуемое число приглашённых мастеров с депозитом для перехода с уровня 1 на 2'),
        ),
        migrations.AddField(
            model_name='settings',
            name='required_invites_level3',
            field=models.IntegerField(default=3, help_text='Требуемое число приглашённых мастеров с депозитом для перехода с уровня 2 на 3'),
        ),
        migrations.AddField(
            model_name='settings',
            name='required_orders_level2',
            field=models.IntegerField(default=10, help_text='Требуемая разница (Completed - Closed) для перехода с уровня 1 на 2'),
        ),
        migrations.AddField(
            model_name='settings',
            name='required_orders_level3',
            field=models.IntegerField(default=30, help_text='Требуемая разница (Completed - Closed) для перехода с уровня 2 на 3'),
        ),
    ]
