# Generated by Django 5.1.2 on 2025-03-05 17:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('serviceapp', '0029_remove_settings_commission_level1_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='workoutcome',
            name='outcome_rating',
            field=models.DecimalField(blank=True, decimal_places=2, help_text='Рейтинг исхода работы (0..5, например)', max_digits=5, null=True),
        ),
    ]
