# Generated by Django 5.1.2 on 2025-03-09 16:45

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('serviceapp', '0030_workoutcome_outcome_rating'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='workoutcome',
            name='service_request',
        ),
        migrations.AlterField(
            model_name='servicerequest',
            name='work_outcome',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='requests', to='serviceapp.workoutcome'),
        ),
    ]
