# Generated by Django 5.1.2 on 2025-03-10 16:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('serviceapp', '0031_remove_workoutcome_service_request_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='master',
            name='joined_group',
            field=models.BooleanField(default=False, help_text='Вступил ли мастер в группу'),
        ),
        migrations.AddField(
            model_name='user',
            name='joined_group',
            field=models.BooleanField(default=False, help_text='Вступил ли клиент в группу'),
        ),
    ]
