# Generated by Django 5.1.2 on 2025-03-10 17:33

from decimal import Decimal
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('serviceapp', '0032_master_joined_group_user_joined_group'),
    ]

    operations = [
        migrations.AddField(
            model_name='settings',
            name='round1_cost_ratio_max',
            field=models.DecimalField(decimal_places=2, default=Decimal('0.30'), help_text='Максимальное значение процента затрат для 1-го круга (1.00 это 100%).', max_digits=4),
        ),
        migrations.AddField(
            model_name='settings',
            name='round1_success_ratio',
            field=models.DecimalField(decimal_places=2, default=Decimal('0.80'), help_text='Минимальное значение процента успешных заявок для 1-го круга (1.00 это 100%).', max_digits=4),
        ),
        migrations.AddField(
            model_name='settings',
            name='round2_cost_ratio_max',
            field=models.DecimalField(decimal_places=2, default=Decimal('0.50'), help_text='Максимальное значение процента затрат для 2-го круга (1.00 это 100%).', max_digits=4),
        ),
        migrations.AddField(
            model_name='settings',
            name='round2_cost_ratio_min',
            field=models.DecimalField(decimal_places=2, default=Decimal('0.30'), help_text='Минимальное значение процента затрат для 2-го круга (1.00 это 100%).', max_digits=4),
        ),
        migrations.AddField(
            model_name='settings',
            name='round2_success_ratio',
            field=models.DecimalField(decimal_places=2, default=Decimal('0.80'), help_text='Минимальное значение процента успешных заявок для 2-го круга (1.00 это 100%).', max_digits=4),
        ),
    ]
