# Generated by Django 5.1.2 on 2025-03-17 17:00

import django.contrib.postgres.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('serviceapp', '0033_settings_round1_cost_ratio_max_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='settings',
            name='allowed_hosts',
            field=django.contrib.postgres.fields.ArrayField(base_field=models.CharField(max_length=255), default=list, help_text='Список разрешенных источников запросов', size=None),
        ),
    ]
