# Generated by Django 5.1.2 on 2025-03-17 17:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('serviceapp', '0034_settings_allowed_hosts'),
    ]

    operations = [
        migrations.AlterField(
            model_name='settings',
            name='allowed_hosts',
            field=models.TextField(default='', help_text='Список разрешенных источников запросов (через запятую)'),
        ),
    ]
